from Property import Property
from CommunityChestCard import CommunityChestCard
from ChanceCard import ChanceCard


class Board:
    properties = list()
    communityChest = list()
    chance = list()

    properties.append(Property(0, "Go", 0, False, 0, "NA"))
    properties.append(Property(1, "Mediterranean Avenue", 60, True, 2, "Dark Purple"))
    properties.append(Property(2, "Community Chest", 0, False, 0, "Community Chest"))
    properties.append(Property(3, "Baltic Avenue", 60, True, 4, "Dark Purple"))
    properties.append(Property(4, "Income Tax", 0, False, 0, "NA"))
    properties.append(Property(5, "Reading Railroad", 200, True, 25, "Station"))
    properties.append(Property(6, "Oriental Avenue", 100, True, 6, "Light Blue"))
    properties.append(Property(7, "Chance", 0, False, 0, "Chance"))
    properties.append(Property(8, "Vermont Avenue", 100, True, 6, "Light Blue"))
    properties.append(Property(9, "Connecticut Avenue", 120, True, 8, "Light Blue"))

    properties.append(Property(10, "Just Visiting/Jail", 0, False, 0, "NA"))
    properties.append(Property(11, "St. Charles Place", 140, True, 10, "Pink"))
    properties.append(Property(12, "Electric Company", 150, True, 0, "Utility"))
    properties.append(Property(13, "States Avenue", 140, True, 10, "Pink"))
    properties.append(Property(14, "Virginia Avenue", 160, True, 12, "Pink"))
    properties.append(Property(15, "Pennsylvania Railroad", 200, True, 25, "Station"))
    properties.append(Property(16, "St. James Place", 180, True, 14, "Orange"))
    properties.append(Property(17, "Community Chest", 0, False, 0, "Community Chest"))
    properties.append(Property(18, "Tennessee Avenue", 180, True, 14, "Orange"))
    properties.append(Property(19, "New York Avenue", 200, True, 16, "Orange"))

    properties.append(Property(20, "Free Parking", 0, False, 0, "NA"))
    properties.append(Property(21, "Kentucky Avenue", 220, True, 18, "Red"))
    properties.append(Property(22, "Chance", 0, False, 0, "Chance"))
    properties.append(Property(23, "Indiana Avenue", 220, True, 18, "Red"))
    properties.append(Property(24, "Illinois Avenue", 240, True, 20, "Red"))
    properties.append(Property(25, "B. & O. Railroad", 200, True, 25, "Station"))
    properties.append(Property(26, "Atlantic Avenue", 260, True, 22, "Yellow"))
    properties.append(Property(27, "Ventnor Avenue", 260, True, 22, "Yellow"))
    properties.append(Property(28, "Water Works", 150, True, 0, "Utility"))
    properties.append(Property(29, "Marvin Gardens", 280, True, 24, "Yellow"))

    properties.append(Property(30, "Go to Jail", 0, False, 0, "NA"))
    properties.append(Property(31, "Pacific Avenue", 300, True, 26, "Green"))
    properties.append(Property(32, "North Carolina Avenue", 300, True, 26, "Green"))
    properties.append(Property(33, "Community Chest", 0, False, 0, "Community Chest"))
    properties.append(Property(34, "Pennsylvania Avenue", 320, True, 28, "Green"))
    properties.append(Property(35, "Short Line", 200, True, 25, "Station"))
    properties.append(Property(36, "Chance", 0, False, 0, "Chance"))
    properties.append(Property(37, "Park Place", 350, True, 35, "Dark Blue"))
    properties.append(Property(38, "Luxury Tax", 0, False, 0, "NA"))
    properties.append(Property(39, "Boardwalk", 400, True, 50, "Dark Blue"))

    communityChest.append(CommunityChestCard(0, "Advance to Go (Collect $200)"))
    communityChest.append(CommunityChestCard(1, "Bank error in your favor. Collect $200"))
    communityChest.append(CommunityChestCard(2, "Doctor's fee. Pay $50"))
    communityChest.append(CommunityChestCard(3, "From sale of stock you get $50"))
    communityChest.append(CommunityChestCard(4, "Get Out of Jail Free"))
    communityChest.append(CommunityChestCard(5, "Go to Jail. Go directly to jail, do not pass Go, do not collect $200"))
    communityChest.append(CommunityChestCard(6, "Holiday fund matures. Receive $100"))
    communityChest.append(CommunityChestCard(7, "Income tax refund. Collect $20"))
    communityChest.append(CommunityChestCard(8, "It is your birthday. Collect $10 from every player"))
    communityChest.append(CommunityChestCard(9, "Life insurance matures. Collect $100"))
    communityChest.append(CommunityChestCard(10, "Pay hospital fee of $100"))
    communityChest.append(CommunityChestCard(11, "Pay school fees of $50"))
    communityChest.append(CommunityChestCard(12, "Receive $25 consultancy fee"))
    communityChest.append(CommunityChestCard(13, "You are assessed for street repair. $40 per house. $115 per hotel"))
    communityChest.append(CommunityChestCard(14, "You have won second prize in a beauty contest. Collect $10"))
    communityChest.append(CommunityChestCard(15, "You inherit $100"))

    chance.append(ChanceCard(0, "Advance to Boardwalk"))
    chance.append(ChanceCard(1, "Advance to Go (Collect $200)"))
    chance.append(ChanceCard(2, "Advance to Illinois Avenue. If you pass Go, collect $200"))
    chance.append(ChanceCard(3, "Advance to St. Charles Place. If you pass Go, collect $200"))
    chance.append(ChanceCard(4, "Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, "
                                "pay wonder twice the rental to which they are otherwise entitled"))
    chance.append(ChanceCard(5, "Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, "
                                "pay wonder twice the rental to which they are otherwise entitled"))
    chance.append(ChanceCard(6, "Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If "
                                "owned, throw dice and pay owner a total of ten times amount thrown"))
    chance.append(ChanceCard(7, "Bank pays you dividend of $50"))
    chance.append(ChanceCard(8, "Get Out of Jail Free"))
    chance.append(ChanceCard(9, "Go Back 3 Spaces"))
    chance.append(ChanceCard(10, "Go to Jail. Go directly to Jail, do not pass Go, do not collect $200"))
    chance.append(ChanceCard(11, "Make general repairs on all your property. For each house pay $25. For each hotel "
                                 "pay $100"))
    chance.append(ChanceCard(12, "Speeding fine $15"))
    chance.append(ChanceCard(13, "Take a trip to Reading Railroad. If you pass Go, collect $200"))
    chance.append(ChanceCard(14, "You have been elected Chairman of the Board. Pay each player $50"))
    chance.append(ChanceCard(15, "Your building loan matures. Collect $150"))

